### ISSUE TITLE
ModuleNotFoundError: No module named 'pinnsjax.data'

### ISSUE THREAD

**Issue by CooloLiu** [rezaakb/pinns-jax#1]
Hi, I would like to ask how to download data when it says here that data can be downloaded automatically, but it doesn't work when I run it.

**Comment by pavleb** [comment]
Is it safe to assume that the ``data`` module from [here](https://github.com/rezaakb/pinns-torch/tree/main/pinnstorch/data) was not translated to this ``JAX`` version?

**Comment by rezaakb** [comment]
Hello @CooloLiu and @pavleb, I apologize for the delayed response. You should now be able to use the `data` module. Unfortunately, it was not pushed to the GitHub repository by mistake.
